### ISSUE TITLE
Exception in HistoryDeal methods (MT5)

### ISSUE THREAD

**Issue by nzyatkov** [vdemydiuk/mtapi#83] opened 2018-02-01 07:10 UTC
Hi,
Do not work HistoryDeal methods in mt5 api client:

```
try
{
  var posId = Mt5ApiClient.PositionGetInteger(ENUM_POSITION_PROPERTY_INTEGER.POSITION_IDENTIFIER); // posId = 7247951
  var history = Mt5ApiClient.HistorySelectByPosition(posId); // history = true
  var historyDealsTotal = Mt5ApiClient.HistoryDealsTotal(); // historyDealsCount  = 4
  var histDealTicket = Mt5ApiClient.HistoryDealGetTicket(0); //  histDealTicket = 6632442
  var histDealPrice = Mt5ApiClient.HistoryDealGetDouble(histDealTicket, ENUM_DEAL_PROPERTY_DOUBLE.DEAL_PRICE); // Exception
}
catch (Exception ex)
{
  // ex.Messsage = "Service connection failed! Ошибка сериализации параметра http://tempuri.org/:command. Сообщение InnerException было \"Тип \"MtApi5.ENUM_DEAL_PROPERTY_DOUBLE\" с именем контракта данных \"ENUM_DEAL_PROPERTY_DOUBLE:http://schemas.datacontract.org/2004/07/MtApi5\" не ожидается. Попробуйте использовать DataContractResolver, если вы используете DataContractSerializer, или добавьте любые статически неизвестные типы в список известных типов - например, используя атрибут KnownTypeAttribute или путем их добавления в список известных типов, передаваемый в сериализатор.\".  Подробнее см. InnerException."
}
```

**Comment by vdemydiuk** [comment] 2018-02-08 15:56
I have investigated this problem on last source code and there is no exception. 
I have fixed this problem in version 1.0.14
What version are you using to make exception?

**Comment by vdemydiuk** [comment] 2018-02-08 16:00
I think this issue is duplicate of Issue #72.

**Comment by nzyatkov** [comment] 2018-02-09 03:01
I cloned 1.0.14 MT5 API version on January 10th., but used MtApi5 installation file from site: http://mtapi4.net/downloads/ Maybe this was the problem?

I'll try to update MT5 to 1.0.15 version and repeat the bug.

**Comment by nzyatkov** [comment] 2018-02-12 05:34
Hi,
In 1.0.15 version it is ok, so I think this issue can be closed. Thank you!

**Comment by vdemydiuk** [comment] 2018-02-12 08:36
Thank you too for testing. I am closing this issue.

**Closed by vdemydiuk** 2018-02-12 08:36 UTC
Labels: bug
